/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyzePanel: typeof import('./src/components/analyze/AnalyzePanel.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    ChatPanel: typeof import('./src/components/chats/ChatPanel.vue')['default']
    copy: typeof import('./src/components/analyze/StandardAnalyzeType/SAAll copy.vue')['default']
    Explorer: typeof import('./src/components/analyze/Explorer.vue')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAAll: typeof import('./src/components/analyze/StandardAnalyzeType/SAAll.vue')['default']
    SAProduct: typeof import('./src/components/analyze/StandardAnalyzeType/SAProduct.vue')['default']
    SocialPanel: typeof import('./src/components/social/SocialPanel.vue')['default']
    StandardAnalyzePanel: typeof import('./src/components/analyze/StandardAnalyzePanel.vue')['default']
    TreeList: typeof import('./src/components/TreeList.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
  }
}
